In [2]:
import tensorflow as tf
from tensorflow import keras
from keras.layers import Dense, Flatten,Conv2D,MaxPooling2D
from keras.models import Sequential

In [16]:
model = Sequential([
                    Conv2D(16,(3,3),activation='relu',input_shape=(800,800,3)),
                    MaxPooling2D(2,2),
                    Conv2D(32,(3,3),activation='relu'),
                    MaxPooling2D(2,2),
                    Conv2D(64,(3,3),activation='relu'),
                    MaxPooling2D(2,2),
                    Conv2D(128,(3,3),activation='relu'),
                    MaxPooling2D(2,2),
                    Flatten(),
                    Dense(128,activation='relu'),
                    Dense(64,activation='relu'),
                    Dense(32,activation='relu'),
                    Dense(10,activation='relu'),
                    Dense(1,activation='sigmoid')
])
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_8 (Conv2D)            (None, 798, 798, 16)      448       
_________________________________________________________________
max_pooling2d_8 (MaxPooling2 (None, 399, 399, 16)      0         
_________________________________________________________________
conv2d_9 (Conv2D)            (None, 397, 397, 32)      4640      
_________________________________________________________________
max_pooling2d_9 (MaxPooling2 (None, 198, 198, 32)      0         
_________________________________________________________________
conv2d_10 (Conv2D)           (None, 196, 196, 64)      18496     
_________________________________________________________________
max_pooling2d_10 (MaxPooling (None, 98, 98, 64)        0         
_________________________________________________________________
conv2d_11 (Conv2D)           (None, 96, 96, 128)      

In [17]:
model.compile(optimizer='RMSProp',loss='binary_crossentropy',metrics=['accuracy'])

In [18]:
dataset = keras.preprocessing.image_dataset_from_directory(directory='drive/MyDrive/arrow-basic-dataset',labels='inferred',image_size=(800,800),batch_size=50)

Found 50 files belonging to 2 classes.


In [21]:
import numpy as np
for i in dataset:
  x_data = np.array(i[0])
  y_data = np.array(i[1])
  print(x_data,y_data)

[[[[231. 231. 231.]
   [231. 231. 231.]
   [231. 231. 231.]
   ...
   [231. 231. 231.]
   [231. 231. 231.]
   [231. 231. 231.]]

  [[231. 231. 231.]
   [231. 231. 231.]
   [231. 231. 231.]
   ...
   [231. 231. 231.]
   [231. 231. 231.]
   [231. 231. 231.]]

  [[231. 231. 231.]
   [231. 231. 231.]
   [231. 231. 231.]
   ...
   [231. 231. 231.]
   [231. 231. 231.]
   [231. 231. 231.]]

  ...

  [[ 49.  51.  72.]
   [ 49.  51.  72.]
   [ 49.  51.  72.]
   ...
   [ 49.  51.  72.]
   [ 49.  51.  72.]
   [ 49.  51.  72.]]

  [[ 49.  51.  72.]
   [ 49.  51.  72.]
   [ 49.  51.  72.]
   ...
   [ 49.  51.  72.]
   [ 49.  51.  72.]
   [ 49.  51.  72.]]

  [[ 49.  51.  72.]
   [ 49.  51.  72.]
   [ 49.  51.  72.]
   ...
   [ 49.  51.  72.]
   [ 49.  51.  72.]
   [ 49.  51.  72.]]]


 [[[255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]
   ...
   [255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]]

  [[255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]
   ...
   [255. 255. 255.]
 

In [19]:
model.fit(dataset,epochs=10)

Epoch 1/10
1/1 [==============================] - 4s 4s/step - loss: 5.3308 - accuracy: 0.5000
Epoch 2/10
1/1 [==============================] - 2s 2s/step - loss: 2690.4512 - accuracy: 0.5000
Epoch 3/10
1/1 [==============================] - 2s 2s/step - loss: 56.9171 - accuracy: 0.5000
Epoch 4/10
1/1 [==============================] - 2s 2s/step - loss: 25.9001 - accuracy: 0.5000
Epoch 5/10
1/1 [==============================] - 2s 2s/step - loss: 12.0259 - accuracy: 0.5000
Epoch 6/10
1/1 [==============================] - 2s 2s/step - loss: 4.4534 - accuracy: 0.5000
Epoch 7/10
1/1 [==============================] - 2s 2s/step - loss: 3.1656 - accuracy: 0.5200
Epoch 8/10
1/1 [==============================] - 2s 2s/step - loss: 0.3664 - accuracy: 0.7800
Epoch 9/10
1/1 [==============================] - 2s 2s/step - loss: 0.2666 - accuracy: 0.9600
Epoch 10/10
1/1 [==============================] - 2s 2s/step - loss: 0.1688 - accuracy: 1.0000


[0.16876813769340515, 1.0]

In [47]:
model.evaluate(x_data)

2/2 [==============================] - 0s 40ms/step - loss: 0.0000e+00 - accuracy: 0.0000e+00


[0.0, 0.0]